### ISSUE TITLE
Identifying Solo Key Serial Number - solo ls?

### ISSUE THREAD

**Issue by dgjansen** [solokeys/solo#376]
I could find no way to identify a somu key out of a list of keys in any way. Or does solo ls do this?

**Why I've tried**
- [x] There's no visible serial number printed on the SOMU device.
- [x] no normal software (Chrome / Windows / ...) tells me which key I'm dealing with. 
- [x] `solo ls` from https://github.com/solokeys/solo-python - does this show an individual key ID? 

**Why it's important**
When deploying security keys in an organization, it's important to be able to identify individual keys. This allows to better ensure a person no longer has access to corporate accounts. It also allows to avoid accidentally returning the wrong key, e.g. a private or  team  key instead of the person's key.

**solo ls**
Is `solo ls` the solution for this and it's not documented? Then I would move this issue to the documentation project (cf. https://support.yubico.com/support/solutions/articles/15000006429-identifying-your-yubikey). However, it would be really helpful to be able to see the key ID at least on the packaging. The keys we've received all had the same ID printed on the packaging. Also it would be great to have something that's easy to use in Windows, e.g. a packaged Windows version of solo-python (cf. https://www.yubico.com/products/services-software/download/yubikey-manager/). (No surprise: yubikey-manager does not detect my solo key.)

**Comment by conorpp** [comment]
Solo devices all have a serial number in the USB descriptor.  `solo ls` is probably the easiest way to view the serial number.  Any solution that can read USB descriptors would work too.  

You can also try the beta of "solo-desktop" for a GUI tool on Windows.

https://github.com/solokeys/solo-desktop/releases

Understand this needs improvement for better organization use, and will prioritize ways to improve -- like printing directly on key and/or packaging.  Appreciate the feedback, and please reach out to hello@solokeys.com for custom packaging or case requirements in the meantime.

Closing since this is more based on host software and the manufacturing side (but we are working on it).
