### ISSUE TITLE
Bootloader security

### ISSUE THREAD

**Issue by jans23** [solokeys/solo#63]
I was watching [this hack](https://media.ccc.de/v/35c3-9563-wallet_fail#t=1227) on the Ledger bootloader verification and wondering if Solo's bootloader is secure against it. 

The entire presentation is very interesting and highly recommended.

**Comment by conorpp** [comment]
Yes it's a pretty good presentation!  We don't have the same issue with Ledger since currently the full memory window is checked before writing :)

https://github.com/solokeys/solo/blob/master/targets/stm32l432/bootloader/bootloader.c#L134

The fault injection attack like they  demonstrate on the Trezor is still potentially an issue, as with most "normal" microcontrollers.
