### ISSUE TITLE
infinite cycle

### ISSUE THREAD

**Issue by merlokk** [solokeys/solo#83]
looks like here is a dead cycle:
https://github.com/solokeys/solo/blob/master/fido2/log.c#L92
am i right?

**Comment by conorpp** [comment]
What do you mean dead cycle?

**Comment by merlokk** [comment]
if we "have lost" TAG_ERR we will exec printf2 it calls LOG it comes to this line and repeat)
stack overflow.

secondly maybe not so good make recursion at microcontroller (if TAG_ERR is ok it will call another time LOG()...  )
and i dont know what will did that exit(1) at microcontroller but i dont think it will be good

**Comment by conorpp** [comment]
exit(1) triggers an infinite loop on MCU, which is good in that it's deterministic.

I think it won't trigger an infinite loop because `TAG_ERR` is a valid tag, and won't cause the `if (i != 0)` to evaluate an extra time.  It's probably more clean to implement this without `printf2` though, so i'll leave open until it's fixed.
